---
- name: Network Getting Started First Playbook with Cisco Switch
  connection: network_cli
  gather_facts: false
  hosts: catalyst2960
  tasks:
    - name: Get config for IOS devices
      ios_facts:
        gather_subset: all
    - name: Display the hostname
      debug:
        msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"
    - name: Change the hostname
      ios_facts:
        backup: yes
        lines:
          - hostname catalyst-2960
    - name: Get config for IOS devices
      ios_facts:
        gather_subset: all
    - name: Display the hostname
      debug:
        msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"
