---
- name: Cisco Switch
  connection: network_cli
  gather_facts: true
  hosts: sshkey
  tasks:
    - name: Get the MAC address table
      ios_command:
        commands:
          - show mac address-table
      register: result1
    - debug:
        var: result1
    - name: Clean up the MAC address table
      ios_command:
        commands:
          - clear mac address-table dynamic
    - name: Get the new MAC address table
      ios_command:
        commands:
          - show mac address-table
      register: result2
    - debug:
        var: result2
