---
- name: Network Getting Started First Playbook with Cisco Switch
  connection: network_cli
  gather_facts: true
  hosts: catalyst2960
  tasks:
    - name: Get config for IOS devices
      ios_facts:
        gather_subset: all
      register: all_subset
    - name: Display the config
      debug:
        #msg: "{{ hostvars[inventory_hostname] }}"
        var: all_subset 
