---
- name: Network Getting Started First Playbook with Cisco Switch
  connection: network_cli
  gather_facts: true
  hosts: catalyst2960
  tasks:
    - name: Get facts
      debug:
        msg:
          - "Hostname: {{ ansible_net_hostname }}"
          - "Image: {{ ansible_net_image }}"
          - "IP Address: {{ ansible_net_all_ipv4_addresses[0] }}"
          - "Interfaces: {{ ansible_net_interfaces }}"
