---
- name: Network Getting Started First Playbook with Cisco Switch
  connection: network_cli
  gather_facts: true
  hosts: catalyst2960
  tasks:
    - name: Get config
      ios_facts:
        gather_subset: hardware
      register: subset_hardware
    - name: Display the config
      debug:
        var: subset_hardware 
    - name: Get config
      ios_facts:
        gather_subset: interfaces
      register: subset_interface
    - name: Display the config
      debug:
        var: subset_interface
