---
- name: Network Getting Started First Playbook with Cisco Switch
  connection: network_cli
  gather_facts: true
  hosts: catalyst2960
  tasks:
    - name: Get the facts
      debug:
        msg:
          - "Hostname: {{ ansible_net_hostname }}"
          - "Image: {{ ansible_net_image }}"
          - "IP Addresses: {{ ansible_facts['ansible_net_all_ipv4_addresses'] }}"
    - name: Execute show run command
      ios_command:
        commands:
          - show run
      register: show_run
    - name: show run output
      debug:
        var: show_run
