---
- name: Cisco Switch
  connection: network_cli
  gather_facts: true
  hosts: sshkey
  tasks:
    - name: configure static route
      ios_static_routes:
        config:
          - address_families:
            - afi: ipv4
              routes:
                - dest: 10.20.30.0/24
                  next_hops:
                    - forward_router_address: 10.20.102.1
                      name: merged_route_1
        state: merged           
      register: route1
    - debug:
        var: route1
