---
- name: Cisco Switch
  connection: network_cli
  gather_facts: true
  hosts: sshkey
  tasks:
    - name: Execute show run command
      ios_command:
        commands:
          - show run
      register: show_run
    - name: show run output
      debug:
        var: show_run
    - name: configure static route
      ios_static_route:
        prefix: 192.168.2.0
        mask: 255.255.255.0
        next_hop: 10.20.102.1
        state: present
      register: route1
    - debug:
        var: route1
